export const tradeNames = [
    "James Smith", "Michael Johnson", "Robert Williams", "David Brown", "Richard Jones",
    "Joseph Garcia", "Thomas Miller", "Charles Davis", "Christopher Rodriguez", "Daniel Martinez",
    "Matthew Hernandez", "Anthony Lopez", "Mark Gonzalez", "Donald Wilson", "Steven Anderson",
    "Paul Thomas", "Andrew Taylor", "Joshua Moore", "Kenneth Jackson", "Kevin Martin",
    "Brian Lee", "George Perez", "Edward Thompson", "Ronald White", "Timothy Harris",
    "Jason Sanchez", "Jeffrey Clark", "Ryan Ramirez", "Jacob Lewis", "Gary Robinson",
    "Nicholas Walker", "Eric Young", "Jonathan Allen", "Stephen King", "Larry Wright",
    "Justin Scott", "Scott Torres", "Brandon Nguyen", "Benjamin Hill", "Samuel Flores",
    "Raymond Green", "Alexander Adams", "Patrick Nelson", "Jack Mitchell", "Dennis Carter",
    "Jerry Roberts", "Tyler Gomez", "Aaron Phillips", "Jose Campbell", "Henry Parker",
    "Adam Evans", "Zachary Edwards", "Nathan Collins", "Douglas Stewart", "Peter Morris",
    "Kyle Murphy", "Walter Rivera", "Ethan Cook", "Jeremy Rogers", "Harold Morgan",
    "Keith Peterson", "Carl Cooper", "Terry Reed", "Russell Bailey", "Lawrence Bell",
    "Stephen Gomez", "Patrick Kelly", "Jack Howard", "Dennis Ward", "Jerry Cox",
    "Tyler Diaz", "Aaron Richardson", "Jose Wood", "Henry Watson", "Adam Brooks",
    "Zachary Bennett", "Nathan Gray", "Douglas James", "Peter Reyes", "Kyle Cruz",
    "Walter Hughes", "Ethan Price", "Jeremy Myers", "Harold Long", "Keith Foster",
    "Carl Sanders", "Terry Ross", "Russell Morales", "Lawrence Powell", "Eric Sullivan",
    "Jonathan Russell", "Stephen Ortiz", "Patrick Jenkins", "Jack Gutierrez", "Dennis Perry",
    "Jerry Butler", "Tyler Barnes", "Aaron Fisher", "Jose Henderson", "Henry Coleman",
    "Adam Simmons", "Zachary Patterson", "Nathan Jordan", "Douglas Reynolds", "Peter Hamilton",
    "Kyle Graham", "Walter Kim", "Ethan Gordon", "Jeremy Washington", "Harold West",
    "Keith Mitchell", "Carl Owens", "Terry Hicks", "Russell Fletcher", "Lawrence Briggs",
    "Alexander Hoffman", "Patrick Carlson", "Dennis Sosa", "Ryan Gibbs", "Matthew Walsh",
    "Anthony Delgado", "David Hayden", "Robert Ellis", "James Harrison", "Michael Holton",
    "Christopher Preston", "Daniel Slade", "Thomas Hines", "William Klein", "Richard Bates",
    "Joseph Bender", "Charles Lloyd", "Steven Gould", "Paul Finch", "Andrew Whalen",
    "Joshua Hogan", "Kevin Montgomery", "Brian Savage", "George Gross", "Ronald Tate",
    "Timothy Flynn", "Jason Rowe", "Jeffrey Hammond", "Ryan Mendez", "Jordan Sutton",
    "Nathan Brady", "Douglas McCormick", "Peter Huffman", "Kyle Holland", "Walter Douglas",
    "Ethan Fleming", "Jeremy Vargas", "Harold Nash", "Keith Steele", "Carl Bowers",
    "Terry Schwartz", "Russell McBride", "Lawrence Dalton", "Eric Kane", "Stephen Hart",
    "Patrick Larson", "Jack Zimmerman", "Dennis Willis", "Jerry Ray", "Tyler Davenport",
    "Aaron Fernandez", "Jose Harvey", "Henry Little", "Adam Craig", "Zachary Santana",
    "Nathan Vega", "Douglas O'Brien", "Peter Serrano", "Kyle Ellison", "Walter Pate",
    "Ethan Whitley", "Jared Glover", "Harold Simon", "Keith Montoya", "Carson Crane",
    "Terry Acosta", "Russell Larson", "Lawrence Franco", "Eric Higgins", "George Welch",
    "Jonathan Lowe", "Stephen Barnes", "Patrick Yates", "Jack O'Connor", "Dennis Brock",
    "Jesse Morrison", "Tyler Haney", "Aaron Flynn", "Jose Munoz", "Henry Mata",
    "Adam Sanderson", "Zachary Best", "Nathan Collier", "Douglas Delaney", "Peter Olson",
    "Kyle McGuire", "Walter Maher", "Ethan Rowe", "Jeremy Huffman", "Harold Dawson",
    "Kevin Kennedy", "Brian Terry", "George Black", "Ronald Stock", "Timothy Bowen",
    "Jason Salazar", "Jeffrey Hendricks", "Ryan May", "Jordan Pennington", "Nathan Fitzgerald",
    "Douglas Rowe", "Peter Briggs", "Kyle O'Connor", "Walter Wagner", "Ethan Chase",
    "Jeremy Hart", "Harold Bates", "Kevin Steele", "Brian Conrad", "George Andersen",
    "Ronald Todd", "Timothy Kaufman", "Jason Slater", "Jeffrey Hensley", "Ryan Witt",
    "Jordan Decker", "Nathan Hoffman", "Peter Lucas", "Kyle Hicks", "Walter Glover",
    "Ethan McDaniel", "Jeremy Foley", "Harold Bryant", "Kevin Elliott", "Brian Hamilton",
    "George Graham", "Ronald Grant", "Timothy Curtis", "Jason Reid", "Jeffrey Owens",
    "Ryan Ingram", "Jordan Reese", "Nathan Warner", "Peter Romo", "Kyle Snyder",
    "Walter Buck", "Ethan Malone", "Jeremy Powers", "Harold Ballard", "Kevin O'Brien",
    "Brian Sutton", "George Pugh", "Ronald Joyner", "Timothy Frost", "Jason Gibson",
    "Jeffrey Lowery", "Ryan Quinn", "Jordan Shea", "Nathan Keller", "Peter Powers",
    "Kylie Berg", "Walter Hunt", "Ethan Savage", "Jeremy Blackwell", "Kevin Holcomb",
    "Brian McLean", "George Brady", "Ronald Osborne", "Timothy Glenn", "Jason Jensen",
    "Jeffrey Byrd", "Ryan Davidson", "Jordan Hopkins", "Nathan May", "Peter Terry",
    "Kyle Henderson", "Walter Weaver", "Ethan Garner", "Jeremy Payne", "Harold Spears",
    "Kevin Hubbard", "Brian Sutton", "George Garrison", "Ronald French", "Timothy Thornton",
    "Jason Dulaney", "Jeffrey Toy", "Ryan Vega", "Nathan Glover", "Peter McFarlane",
    "Kylie Goodwin", "Walter Malone", "Ethan Buckley", "Jeremy Frost", "Harold Randall",
    "Kevin Huffman", "Brian Terry", "George Skaggs", "Ronald Bowers", "Timothy Whitley",
    "Jason Hogan", "Jeffrey Reeder", "Ryan Hines", "Jordan Cates", "Nathan Sexton",
    "Peter Cooley", "Kyle Vining", "Walter Crain", "Ethan Maynard", "Jeremy Early",
    "Harold Lockhart", "Kevin Guthrie", "Brian Little", "George Willis", "Ronald Caldwell",
    "Timothy Drake", "Jason Crosby", "Jeffrey Santana", "Ryan Gibbs", "Jordan Mercer",
    "Nathan Todd", "Peter Bullard", "Kyle Salazar", "Walter Humphrey", "Ethan Bowers",
    "Jeremy Yates", "Harold O'Donnell", "Kevin Wagner", "Brian McCall", "George Cleveland",
    "Ronald Boone", "Timothy Hogan", "Jeffrey McQueen", "Ryan Sutton", "Jordan Vance",
    "Nathan Chase", "Peter Moody", "Kyle Ryan", "Walter Nichols", "Ethan Bradley",
    "Jeremy Coffey", "Harold Matthews", "Kevin Dunn", "Brian Knight", "George Bentley",
    "Ronald Elliott", "Timothy Burgess", "Jason Lowe", "Ryan Dotson", "Jordan Sparks",
    "Nathan Parker", "Peter Owens", "Kyle Hickman", "Walter Lucas", "Ethan Fernandez",
    "Jeremy Sims", "Harold Collins", "Kevin Jennings", "Brian Russell", "George Fields",
    "Ronald Reynolds", "Timothy Stevens", "Jason Payne", "Ryan Andrews", "Jordan Perry",
    "Nathan Schmidt", "Peter Craig", "Kyle Walsh", "Walter Hamilton", "Ethan Graham",
    "Jeremy Nash", "Harold Cole", "Kevin Ellis", "Brian Morrison", "George Freeman",
    "Ronald Daniels", "Timothy Montgomery", "Jared Richards", "Ryan Wallace", "Jordan Woods",
    "Nathan Montgomery", "Peter Shaw", "Kyle Sullivan", "Edward Morgan", "Ethan Cole",
    "Jeremy O'Connor", "Harold Stevens", "Kevin Robinson", "Brian Wright", "George Thompson",
    "Ronald Reed", "Timothy Morgan", "Jared Watson", "Ryan Brooks", "Jordan Kelly",
    "Nathan Sanders", "Peter Price", "Kyle Bennett", "Walter Cook", "Ethan Bailey",
    "Jeremy Cooper", "Harold Richardson", "Kevin Cox", "Ryan Howard", "Jordan Ward",
    "Nathan Torres", "Peter Peterson", "Kyle Gray", "Walter James", "Ethan Reyes",
    "Jeremy Rogers", "Harold Harris", "Brian Lewis", "George Clark", "Ronald Robinson",
    "Timothy Walker", "Jared Young", "Ryan Allen", "Jordan Hall", "Nathan Wright",
    "Lopez King", "Kyle Scott", "Walter Green", "Ethan Baker", "Jeremy Adams",
    "Harold Nelson", "Kevin Hill", "Brian Ramirez", "George Mitchell", "Ronald Perez",
    "Timothy Roberts", "Jared Carter", "Ryan Phillips", "Nathan Campbell", "Peter Evans",
    "Kyle Turner", "Walter Torres", "Ethan Parker", "Jeremy Collins", "Harold Edwards",
    "Kevin Stewart", "Brian Flores", "George Morris", "Ronald Nguyen", "Timothy Murphy",
    "Jared Rivera", "Ryan Cook", "Jordan Rogers", "Nathan Morgan", "Peter Peterson",
    "Kyle Cooper", "Walter Reed", "Ethan Bailey", "Jeremy Bell", "Harold Gomez",
    "Kevin Kelly", "Brian Howard", "George Ward", "Ronald Cox", "Timothy Diaz",
    "Jared Richardson", "Ryan Wood", "Jordan Watson", "Nathan Brooks", "Peter Bennett",
    "Kyle Gray", "Walter James", "Ethan Reyes", "Jeremy Cruz", "Harold Hughes",
    "Kevin Price", "Brian Myers", "George Long", "Ronald Foster", "Timothy Sanders",
    "Jared Ross", "Ryan Morales", "Nathan Powell", "Peter Sullivan", "Kyle Russell",
    "Walter Ortiz", "Ethan Jenkins", "Jeremy Perry", "Harold Butler", "Kevin Barnes",
    "Brian Fisher", "George Henderson", "Ronald Coleman", "Timothy Simmons", "Jared Patterson",
    "Ryan Jordan", "Nathan Reynolds", "Peter Hamilton", "Kyle Graham", "Walter Kim",
    "Ethan Gordon", "Jeremy Washington", "Harold West", "Kevin Mitchell", "Brian Owens",
    "George Hicks", "Ronald Sosa", "Timothy Gibbs", "Jared Walsh", "Ryan Delgado",
    "Jordan Hayden", "Nathan Ellis", "Peter Harrison", "Kyle Holton", "Walter Klein",
    "Ethan Bates", "Jeremy Bender", "Harold Lloyd", "Kevin Gould", "Brian Finch",
    "George Whalen", "Ronald Hogan", "Timothy Montgomery", "Jared Savage", "Ryan Gross",
    "Jordan Tate", "Nathan Flynn", "Peter Rowe", "Kyle Hammond", "Walter Mendez",
    "Ethan Sutton", "Jeremy Brady", "Harold McCormick", "Kevin Huffman", "Brian Holland",
    "George Douglas", "Ronald Fleming", "Timothy Vargas", "Jared Nash", "Ryan Steele",
    "Jordan Bowers", "Nathan Schwartz", "Peter McBride", "Kyle Dalton", "Walter Kane",
    "Ethan Hart", "Jeremy Larson", "Harold Zimmerman", "Kevin Willis", "Brian Ray",
    "George Davenport", "Ronald Fernandez", "Timothy Harvey", "Jared Little", "Ryan Craig",
    "Jordan Santana", "Nathan Vega", "Peter O'Brien", "Kyle Serrano", "Walter Ellison",
    "Ethan Pate", "Jeremy Whitley", "Harold Glover", "Kevin Simon", "Brian Montoya",
    "George Crane", "Ronald Acosta", "Timothy Larson", "Jared Franco", "Ryan Higgins",
    "Jordan Welch", "Nathan Lowe", "Peter Barnes", "Kyle Yates", "Walter O'Connor",
    "Ethan Brock", "Jeremy Morrison", "Harold Haney", "Kevin Flynn", "Brian Munoz",
    "George Mata", "Ronald Sanderson", "Timothy Best", "Jared Collier", "Ryan Delaney",
    "Jordan Olson", "Nathan McGuire", "Peter Maher", "Kyle Rowe", "Walter Huffman",
    "Ethan Dawson", "Jeremy Kennedy", "Harold Terry", "Kevin Black", "Brian Stock",
    "Ronald Bowen", "Timothy Salazar", "Jared Hendricks", "Ryan May", "Jordan Pennington",
    "Nathan Fitzgerald", "Peter Lucas", "Kyle Hicks", "Walter Glover", "Ethan McDaniel",
    "Jeremy Foley", "Harold Bryant", "Kevin Elliott", "Brian Hamilton", "George Graham",
    "Ronald Grant", "Timothy Curtis", "Jared Reid", "Ryan Owens", "Jordan Ingram",
    "Nathan Reese", "Peter Warner", "Kyle Romo", "Walter Snyder", "Ethan Buck",
    "Jeremy Malone", "Harold Powers", "Kevin O'Brien", "Brian Sutton", "George Pugh",
    "Ronald Joyner", "Timothy Frost", "Jared Gibson", "Ryan Lowery", "Jordan Quinn",
    "Nathan Shea", "Peter Keller", "Kyle Powers", "Walter Hunt", "Ethan Savage",
    "Jeremy Blackwell", "Harold Holcomb", "Kevin McLean", "Brian Brady", "George Osborne",
    "Ronald Glenn", "Timothy Jensen", "Jared Byrd", "Ryan Davidson", "Jordan Hopkins",
    "Nathan May", "Peter Terry", "Kyle Henderson", "Walter Weaver", "Ethan Garner",
    "Jeremy Payne", "Harold Spears", "Kevin Hubbard", "Brian Sutton", "George Garrison",
    "Ronald French", "Timothy Thornton", "Jared Dulaney", "Ryan Toy", "Jordan Vega",
    "Nathan Glover", "Peter McFarlane", "Kyle Goodwin", "Walter Malone", "Ethan Buckley",
    "Jeremy Frost", "Harold Randall", "Kevin Huffman", "Brian Terry", "George Skaggs",
    "Ronald Bowers", "Timothy Whitley", "Jared Hogan", "Ryan Reeder", "Jordan Hines",
    "Nathan Cates", "Peter Sexton", "Kyle Cooley", "Walter Vining", "Ethan Crain",
    "Jeremy Maynard", "Harold Early", "Kevin Lockhart", "Brian Guthrie", "George Little",
    "Ronald Willis", "Timothy Caldwell", "Jared Drake", "Ryan Crosby", "Jordan Santana",
    "Nathan Gibbs", "Peter Mercer", "Kyle Todd", "Walter Bullard", "Ethan Salazar",
    "Jeremy Humphrey", "Harold Bowers", "Kevin Yates", "Brian O'Donnell", "George Wagner",
    "Ronald McCall", "Timothy Cleveland", "Jared Boone", "Ryan Hogan", "Jordan McQueen",
    "Nathan Sutton", "Peter Vance", "Kyle Chase", "Walter Moody", "Ethan Ryan",
    "Jeremy Nichols", "Harold Bradley", "Kevin Coffey", "Brian Matthews", "George Dunn",
    "Ronald Knight", "Timothy Bentley", "Jared Elliott", "Ryan Burgess", "Jordan Lowe",
    "Nathan Dotson", "Peter Sparks", "Kyle Parker", "Walter Owens", "Ethan Hickman",
    "Jeremy Lucas", "Harold Fernandez", "Kevin Sims", "Brian Collins", "George Jennings",
    "Ronald Russell", "Timothy Fields", "Jared Reynolds", "Ryan Stevens", "Jordan Payne",
    "Nathan Andrews", "Peter Perry", "Kyle Schmidt", "Walter Craig", "Ethan Walsh",
    "Jeremy Hamilton", "Harold Nash", "Kevin Cole", "Brian Ellis", "George Morrison",
    "Ronald Freeman", "Timothy Daniels", "Jared Montgomery", "Ryan Richards", "Jordan Wallace",
    "Nathan Woods", "Peter Montgomery", "Kyle Shaw", "Walter Sullivan", "Ethan Morgan",
    "Jeremy Cole", "Harold O'Connor", "Kevin Stevens", "Brian Robinson", "George Wright",
    "Ronald Thompson", "Timothy Reed", "Jared Watson", "Ryan Brooks", "Jordan Kelly",
    "Nathan Sanders", "Peter Price", "Kyle Bennett", "Walter Cook", "Ethan Bailey",
    "Jeremy Cooper", "Harold Richardson", "Kevin Cox", "Ryan Howard", "Jordan Ward",
    "Nathan Torres", "Peter Peterson", "Kyle Gray", "Walter James", "Ethan Reyes",
    "Jeremy Rogers", "Harold Harris", "Brian Lewis", "George Clark", "Ronald Robinson",
    "Timothy Walker", "Jared Young", "Ryan Allen", "Jordan Hall", "Nathan Wright",
    "Lopez King", "Kyle Scott", "Walter Green", "Ethan Baker", "Jeremy Adams"
];

export const countries = [
    "United States", "United Kingdom", "Canada", "Australia", "Germany",
    "France", "Italy", "Spain", "Netherlands", "Switzerland",
    "Sweden", "Norway", "Denmark", "Finland", "Belgium",
    "Austria", "Ireland", "Portugal", "Greece", "Poland",
    "Czech Republic", "Hungary", "Romania", "Bulgaria", "Croatia",
    "Slovenia", "Slovakia", "Lithuania", "Latvia", "Estonia",
    "Luxembourg", "Monaco", "Liechtenstein", "Malta", "Cyprus",
    "Japan", "South Korea", "Taiwan", "Singapore", "Hong Kong",
    "China", "India", "Thailand", "Vietnam", "Indonesia",
    "Malaysia", "Philippines", "New Zealand", "United Arab Emirates", "Qatar",
    "Saudi Arabia", "Kuwait", "Bahrain", "Oman", "Israel",
    "Turkey", "Lebanon", "Jordan", "Mexico", "Brazil",
    "Argentina", "Chile", "Colombia", "Peru", "Uruguay",
    "Paraguay", "Ecuador", "Venezuela", "Costa Rica", "Panama"
];

export const actionTypes = [
    "traded",
    "withdrew",
    "profited"
];
